# Generated by Django 2.1.7 on 2019-06-06 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=200)),
                ('ects', models.FloatField()),
                ('students', models.ManyToManyField(to='student.Student')),
            ],
        ),
    ]
